### ISSUE TITLE
关于速度问题

### ISSUE THREAD

**Issue by eivaltsec** [chengstone/FindFaceInVideo#1]
人脸特征值对比能做到实时么(24fps/s)，谢谢楼主

**Comment by chengstone** [comment]
当前这个代码确实没有考虑到速度问题，实际应用中是不行的。我在今年初重新实现了视频中找人，完全抛弃了caffe，seetaface和OpenCV，只用TensorFlow实现。使用冰与火之歌最后一季的某一集做测试，1小时20分的视频使用了16分钟。代码暂时不能放出，因为有公司花钱了。能不能做到实时我不确定，你可以看看新出的Yolo v3。

**Comment by eivaltsec** [comment]
好的，多谢楼主
